import{a as h,S as I,i as d}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const g of o.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&s(g)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();let f=1;const P=async(e,r=40)=>{const l="https://pixabay.com/api/",s=document.getElementById("loader");s.style.display="block";try{const t=await h.get(l,{params:{key:"47161865-40d939b38272e547a09e56cd8",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:r,page:f}});return s.style.display="none",t.data}catch(t){throw s.style.display="none",console.error("Error fetching images:",t),t}},S=()=>{f=1},b=()=>{f+=1},w=e=>e.map(r=>B(r)).join(""),B=e=>`
    <li class='gallery-item'>
      <a href="${e.largeImageURL}">
        <img alt="${e.tags}" src="${e.webformatURL}" class='gallery-image'/>
      </a>
      <ul class='list-info'>
      ${i("Likes",e.likes)}
      ${i("Views",e.views)}
      ${i("Comments",e.comments)}
      ${i("Downloads",e.downloads)}
    </ul>
  </li>
`,i=(e,r)=>`
  <li class='item-info'>
    <p class='title-info'>${e}</p>
    <p class='count-info'>${r}</p>
  </li>
`;document.getElementById("loadMoreButton").addEventListener("click",()=>{loadMore()});const y="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=",p=document.querySelector(".form"),u=document.querySelector("ul.gallery"),n=document.querySelector(".loader"),a=document.querySelector(".load-more");let E=new I(".gallery a",{captionsData:"alt",captionDelay:250});d.settings({timeout:4e3,position:"topRight"});let c="",C=1,m=0;const v=e=>{if(e.preventDefault(),u.innerHTML="",n.style.display="block",a.style.display="none",c=e.target.elements.search.value.trim(),!c){d.error({iconUrl:y,iconColor:"#fff",imageWidth:24,messageColor:"#fff",message:"Please write a query for search"}),n.style.display="none";return}S(),A(c)},A=e=>{P(e).then(({hits:r,totalHits:l})=>{if(r.length===0){d.error({iconUrl:y,iconColor:"#fff",imageWidth:24,messageColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none";return}const s=w(r);u.innerHTML+=s,n.style.display="none",m=Math.ceil(l/40),R(m),E.refresh(),p.reset(),b()}).catch(r=>{console.error("Error fetching images:",r),d.error({iconUrl:y,iconColor:"#fff",imageWidth:24,messageColor:"#fff",message:"Error fetching images. Please try again later."}),n.style.display="none"})},L=()=>{n.style.display="block",a.style.display="none",A(c).then(()=>{n.style.display="none";const e=document.querySelector(".gallery-item");if(e.length>0){const r=e[e.length-40];r&&r.scrollIntoView({behavior:"smooth",block:"start"})}})},R=e=>{C>=e?a.style.display="none":a.style.display="block"};p.addEventListener("submit",v);a.addEventListener("click",L);
//# sourceMappingURL=index.js.map
